### PR TITLE
Show package loading status

### PR DESCRIPTION
**Pull request by kravets-levko**
As described in issue openspending/openspending#1118 except on one thing: progress will not be shown, because for this I need to load entire resource datafile and count lines in it (API does not return % of processed rows; in Packager we already have datafile in memory, and there is only one file - Admin may check for multiple files, so it will lead to much more memory and time consumption than in Packager).

### CODE REVIEW

**Comment by akariv** [comment]
@kravets-levko perhaps we can embed the # of rows as part of the resource descriptor? We can add this in the packager and read this here.

**Comment by kravets-levko** [comment]
Yes, we can, I think. But then what about packages uploaded by other tools (don't know, - there is python cli AFAIK, maybe something else)?

**Comment by kravets-levko** [comment]
I think, we can just show a number of processed rows (returned by API): user will see that app is doing something - it's better than nothing, IMHO.

**Comment by akariv** [comment]
If there's no 'total rows' indicator then we could fallback to simply not showing progress (or showing the '# of processed lines' message as you suggested).

So basically:
- has 'total_rows' property: show progress bar
- doesn't have: show # of rows counter

**Comment by kravets-levko** [comment]
Okay, got it. Will implement it tomorrow

**Comment by kravets-levko** [comment]
@akariv Added progress, as we decided. Also please look at this PR: openspending/os-packager/pull/102

**Review by akariv — APPROVED** [review]

**Pull request merged**
