### PR TITLE
Quick fix for os 1185

### PR DESCRIPTION
**Pull request by Vanuan**
Fix for https://github.com/openspending/openspending/issues/1185

### CODE REVIEW

**Comment by akariv** [comment]
Thanks for the PR @Vanuan !

**Review by kravets-levko — APPROVED** [review]

**Comment by kravets-levko** [comment]
@akariv @Vanuan Should the same fix be applied to "View" button (OS Viewer URL)?

**Comment by Vanuan** [comment]
Huh? The "View" button already has `target="_blank"`. If you have a better fix, it would be great.

**Comment by Vanuan** [comment]
This is a naive approach. I don't know how it's supposed to work. I expect that you know more about it.

If it's possible to open it in the same window, it would've been much more seamless.

**Comment by kravets-levko** [comment]
@Vanuan Angular router handles clicks on `<a>` tags to allow navigation without reloading page. Two cases when it does not intercept links: external links (to another domain) (notice: in case of OS instance, all apps (Admin, Explorer, Viewer and Packager) are actually located on the same domain, so Angular intercepts such links, even if they have `http://` schema), and `<a>` tags with `target` attribute. So your solution is right. And if you don't want to reload page - you can specify other target - `target="_self"` - it will load link in the same frame.

**Comment by kravets-levko** [comment]
@Vanuan If you don't wish to add something to this PR - I'll merge it as it looks good to me.

**Comment by Vanuan** [comment]
Well, I'm still wondering why the View button works, while it doesn't explicitly contain `target` attribute.

**Pull request merged**
